/**
 * 
 */
package seahorse.internal.business.katavuccolservice.api;

/**
 * @author sajanmje
 *
 */
public interface IKatavuccolServiceApiMapper {	

	/*CredentialResponse mapCredentialsResponse(CredentialResponseMessageEntity credentialsResMessageEntity);

	CredentialRequestMessageEntity mapCredentialRequestMessageEntity(CreateCredentialRequestModel credentialRequest,String userid,String categoryId, HttpServletRequest httpRequest);

	GetCredentialMessageEntity mapGetCredentialMessageEntity(String userid,String categoryId, HttpServletRequest httpRequest);

	List<Credential> mapCredential(GetCredentialsMessageEntity getCredentialsMessageEntity);

	CredentialResponse mapCredentialsResponse(CredentialResponseMessageEntity credentialsResMessageEntity, CredentialRequestMessageEntity credentialMessageEntity);

	//UpdateCredentialMessageEntity mapUpdateCredentialRequestMessageEntity(UpdateCredentialRequest updateCredentialRequest, String userid,String categoryId, String credentialId,HttpServletRequest httpRequest);

	UpdateCredentialResponse mapUpdateCredentialResponse(UpdateCredentialResponseMessageEntity updateCredentialResponseMessageEntity,UpdateCredentialMessageEntity updateCredentialMessageEntity);

	DeleteCredentialMessageEntity mapDeleteCredentialRequestMessageEntity(String userid,String categoryId, String credentialId,HttpServletRequest httpRequest);

	DeleteCredentialResponse mapDeleteCredentialResponse(DeleteCredentialResMsgEntity deleteCredentialResponseMessageEntity,DeleteCredentialMessageEntity deleteCredentialMessageEntity);

	CategoryRequestMessageEntity mapCategoryRequestMessageEntity(CategoryRequest categoryRequest, String userid, HttpServletRequest httpRequest);

	CategoryResponse mapCategoryResponse(CategoryResponseMessageEntity categoryResponseMessageEntity,CategoryRequestMessageEntity categoryMessageEntity);

	DeleteCategoryRequestMessageEntity mapDeleteCategoryRequestMessageEntity(String userid, String categoryId,HttpServletRequest httpRequest);

	DeleteCategoryResponseModel mapDeleteCategoryResponse(DeleteCategoryResponseMessageEntity deleteCategoryResponseMessageEntity,DeleteCategoryRequestMessageEntity deleteCategoryRequestMessageEntity);

	UpdateCategoryMessageEntity mapUpdateCategoryRequestMessageEntity(UpdateCategoryRequestModel updateCategoryRequest,
			String userid, String categoryId, HttpServletRequest httpRequest);

	UpdateCategoryResponseModel mapUpdateCategoryResponse(
			UpdateCategoryResponseMessageEntity updateCategoryResponseMessageEntity,
			UpdateCategoryMessageEntity updateCategoryMessageEntity);

	CredentialTypeRequestMessageEntity mapCredentialTypeRequestMessageEntity(
			CreateCredentialTypeRequestModel credentialTypeRequest, 
			String userid, 
			HttpServletRequest httpRequest);

	CreateCredentialTypeResponseModel mapCredentialTypeResponse(
			CredentialTypeResponseMessageEntity credentialTypeResponseMessageEntity,
			CredentialTypeRequestMessageEntity credentialTypeRequestMessageEntity);

	UpdateCredentialTypeMessageEntity mapUpdateCredentialRequestMessageEntity(
			UpdateCredentialTypeRequestModel updateCredentialTypeRequest, String userid, String credentialId,
			HttpServletRequest httpRequest);

	UpdateCredentialTypeResponseModel mapUpdateCredentialTypeResponse(
			UpdateCredentialResponseMessageEntity updateCredentialResponseMessageEntity,
			UpdateCredentialTypeMessageEntity updateCredentialTypeMessageEntity);

	DeleteCredentialTypeResponseModel mapDeleteCredentialTypeResponse(
			DeleteCredentialTypeResMsgEntity deleteCredentialTypeResMsgEntity,
			DeleteCredentialTypeReqMsgEntity deleteCredentialTypeRequestMessageEntity);

	DeleteCredentialTypeReqMsgEntity mapDeleteCredentialTypeRequestMessageEntity(String userid,
			String credentialTypeId, HttpServletRequest httpRequest);

	GetCategoryMessageEntity mapGetCategoryMessageEntity(String userid, HttpServletRequest httpRequest);

	GetCredentialValueMessageEntity mapGetCredentialValueMessageEntity(String userid,String categoryId,String credentialId, 
			HttpServletRequest httpRequest,GetCredentialValueRequest getCredentialValueRequest);

	GetCredentialByUserIdMessageEntity mapGetCredentialByUserIdMessageEntity(String userid);

	CredentialTypeByUserIdMsgEntity mapCredentialTypeByUserIdMsgEntity(String userid);

	CreateCredentialTypeMsgEntity mapCreateCredentialTypeMsgEntity(CreateCredentialTypeRequestModel credentialTypeRequest,String userid, 
			HttpServletRequest httpRequest);

	CreateCredentialTypeResponseModel mapCredentialTypeResponse(CreateCredentialTypeResMsgEntity createCredentialTypeResMsgEntity,
			CreateCredentialTypeMsgEntity createCredentialTypeMsgEntity);

	CredentialTypeByUserIdMsgEntity mapCredentialTypeByUserIdMsgEntity(String userid, String id);*/

}
